spring.application.name=UDiplomacy

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/udiplomacy

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/udiplomacy
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
app.jwt.secret=c2VjcmV0LWtleS1mb3ItZGlwbG9tYWN5LWJhY2tlbmQtanNvbi13ZWItdG9rZW4tMjAyNg==
app.jwt.expiration-ms=86400000

# Server
server.port=8080
