package com.ulises.udiplomacy.domain.game;

import com.ulises.udiplomacy.domain.game.enums.ProvinceType;

import java.util.List;
import java.util.Map;

public final class TestMapFactory {

    public static GameMap createClassicMap() {
        return new GameMap("test", "Test Map", List.of(
                new Province("LON", ProvinceType.COASTAL, new Nation("ENGLAND"), true, null,
                        Map.of("YOR", null, "WAL", null, "NTH", null, "ENG", null)),
                new Province("YOR", ProvinceType.COASTAL, null, false, null,
                        Map.of("LON", null, "NTH", null)),
                new Province("WAL", ProvinceType.COASTAL, null, false, null,
                        Map.of("LON", null, "ENG", null, "IRI", null)),
                new Province("EDI", ProvinceType.COASTAL, new Nation("ENGLAND"), true,
                        List.of(new Coast("north"), new Coast("south")),
                        Map.of("NTH", null, "NWG", null, "CLY", null)),
                new Province("CLY", ProvinceType.INLAND, null, false, null,
                        Map.of("EDI", null, "NWG", null, "NAO", null)),
                new Province("NTH", ProvinceType.SEA, null, false, null,
                        Map.of("LON", null, "YOR", null, "EDI", null, "NWG", null,
                                "SKA", null, "DEN", null, "HOL", null, "BEL", null, "ENG", null)),
                new Province("ENG", ProvinceType.SEA, null, false, null,
                        Map.of("LON", null, "WAL", null, "NTH", null, "IRI", null,
                                "MID", null, "BEL", null, "PIC", null)),
                new Province("NWG", ProvinceType.SEA, null, false, null,
                        Map.of("EDI", null, "CLY", null, "NTH", null, "SKA", null,
                                "NOR", null, "BAR", null)),
                new Province("IRI", ProvinceType.SEA, null, false, null,
                        Map.of("WAL", null, "ENG", null, "NAO", null)),
                new Province("NAO", ProvinceType.SEA, null, false, null,
                        Map.of("CLY", null, "IRI", null, "MID", null, "WES", null)),
                new Province("MID", ProvinceType.SEA, null, false, null,
                        Map.of("ENG", null, "NAO", null, "WES", null, "LYO", null)),
                new Province("BEL", ProvinceType.COASTAL, null, false, null,
                        Map.of("NTH", null, "ENG", null, "PIC", null, "RUH", null, "BUR", null)),
                new Province("PIC", ProvinceType.COASTAL, null, false, null,
                        Map.of("ENG", null, "BEL", null, "BRE", null, "PAR", null, "BUR", null)),
                new Province("BRE", ProvinceType.COASTAL, new Nation("FRANCE"), true, null,
                        Map.of("PIC", null, "PAR", null, "GAS", null, "ENG", null)),
                new Province("PAR", ProvinceType.INLAND, new Nation("FRANCE"), true, null,
                        Map.of("PIC", null, "BRE", null, "GAS", null, "BUR", null)),
                new Province("GAS", ProvinceType.COASTAL, null, false, null,
                        Map.of("BRE", null, "PAR", null, "BUR", null, "MAR", null, "SPA", null)),
                new Province("BUR", ProvinceType.INLAND, null, false, null,
                        Map.of("BEL", null, "PIC", null, "PAR", null, "GAS", null, "MAR", null, "MUN", null, "RUH", null)),
                new Province("MAR", ProvinceType.COASTAL, new Nation("FRANCE"), true, null,
                        Map.of("GAS", null, "BUR", null, "PIE", null, "LYO", null, "SPA", null)),
                new Province("SPA", ProvinceType.COASTAL, null, false,
                        List.of(new Coast("north"), new Coast("south")),
                        Map.of("GAS", null, "MAR", null, "POR", null, "MID", null, "WES", null, "LYO", null)),
                new Province("POR", ProvinceType.COASTAL, null, false, null,
                        Map.of("SPA", null, "MID", null)),
                new Province("PIE", ProvinceType.INLAND, null, false, null,
                        Map.of("MAR", null, "LYO", null, "TUS", null, "VEN", null, "TYR", null)),
                new Province("LYO", ProvinceType.SEA, null, false, null,
                        Map.of("MAR", null, "SPA", null, "MID", null, "WES", null, "TUS", null, "PIE", null)),
                new Province("WES", ProvinceType.SEA, null, false, null,
                        Map.of("NAO", null, "MID", null, "LYO", null, "TUN", null)),
                new Province("TUS", ProvinceType.COASTAL, null, false, null,
                        Map.of("PIE", null, "LYO", null, "ROM", null)),
                new Province("ROM", ProvinceType.COASTAL, new Nation("ITALY"), true, null,
                        Map.of("TUS", null, "VEN", null, "APU", null, "NAP", null, "TYS", null)),
                new Province("VEN", ProvinceType.COASTAL, new Nation("ITALY"), true, null,
                        Map.of("PIE", null, "TYR", null, "TRI", null, "APU", null, "ROM", null)),
                new Province("TYR", ProvinceType.INLAND, null, false, null,
                        Map.of("PIE", null, "VEN", null, "TRI", null, "VIE", null, "BOH", null, "MUN", null)),
                new Province("TRI", ProvinceType.COASTAL, new Nation("AUSTRIA"), true, null,
                        Map.of("VEN", null, "TYR", null, "VIE", null, "BUD", null, "SER", null, "ALB", null, "ADR", null)),
                new Province("ADR", ProvinceType.SEA, null, false, null,
                        Map.of("TRI", null, "ALB", null, "ION", null, "APU", null)),
                new Province("APU", ProvinceType.COASTAL, null, false, null,
                        Map.of("VEN", null, "ROM", null, "NAP", null, "ION", null, "ADR", null)),
                new Province("NAP", ProvinceType.COASTAL, new Nation("ITALY"), true, null,
                        Map.of("ROM", null, "APU", null, "ION", null, "TYS", null)),
                new Province("TYS", ProvinceType.SEA, null, false, null,
                        Map.of("ROM", null, "NAP", null, "LYO", null, "ION", null, "TUN", null)),
                new Province("ION", ProvinceType.SEA, null, false, null,
                        Map.of("APU", null, "NAP", null, "ADR", null, "ALB", null, "GRE", null, "TYS", null, "TUN", null)),
                new Province("ALB", ProvinceType.COASTAL, null, false, null,
                        Map.of("TRI", null, "ADR", null, "ION", null, "GRE", null, "SER", null)),
                new Province("GRE", ProvinceType.COASTAL, null, false, null,
                        Map.of("ALB", null, "ION", null, "SER", null, "BUL", null, "AEG", null)),
                new Province("SER", ProvinceType.INLAND, null, false, null,
                        Map.of("TRI", null, "ALB", null, "GRE", null, "BUD", null, "RUM", null, "BUL", null)),
                new Province("BUL", ProvinceType.COASTAL, null, false,
                        List.of(new Coast("east"), new Coast("north")),
                        Map.of("GRE", null, "SER", null, "RUM", null, "BLA", null, "CON", null, "AEG", null)),
                new Province("RUM", ProvinceType.COASTAL, null, false, null,
                        Map.of("SER", null, "BUL", null, "BLA", null, "SEV", null, "UKR", null, "BUD", null)),
                new Province("BUD", ProvinceType.INLAND, new Nation("AUSTRIA"), true, null,
                        Map.of("TRI", null, "TYR", null, "VIE", null, "GAL", null, "UKR", null, "RUM", null, "SER", null)),
                new Province("VIE", ProvinceType.INLAND, new Nation("AUSTRIA"), true, null,
                        Map.of("TYR", null, "TRI", null, "BUD", null, "GAL", null, "BOH", null)),
                new Province("BOH", ProvinceType.INLAND, null, false, null,
                        Map.of("TYR", null, "VIE", null, "GAL", null, "MUN", null, "SIL", null)),
                new Province("GAL", ProvinceType.INLAND, null, false, null,
                        Map.of("VIE", null, "BUD", null, "UKR", null, "WAR", null, "SIL", null, "BOH", null)),
                new Province("MUN", ProvinceType.INLAND, new Nation("GERMANY"), true, null,
                        Map.of("BUR", null, "RUH", null, "TYR", null, "BOH", null, "SIL", null, "BER", null)),
                new Province("RUH", ProvinceType.INLAND, null, false, null,
                        Map.of("BEL", null, "BUR", null, "MUN", null, "KIE", null, "HOL", null)),
                new Province("KIE", ProvinceType.COASTAL, new Nation("GERMANY"), true, null,
                        Map.of("RUH", null, "HOL", null, "DEN", null, "BAL", null, "BER", null, "HEL", null)),
                new Province("HOL", ProvinceType.COASTAL, null, false, null,
                        Map.of("NTH", null, "BEL", null, "RUH", null, "KIE", null, "DEN", null, "HEL", null)),
                new Province("DEN", ProvinceType.COASTAL, null, false, null,
                        Map.of("NTH", null, "SKA", null, "SWE", null, "BAL", null, "KIE", null, "HEL", null, "HOL", null)),
                new Province("HEL", ProvinceType.SEA, null, false, null,
                        Map.of("KIE", null, "HOL", null, "DEN", null, "BER", null)),
                new Province("BAL", ProvinceType.SEA, null, false, null,
                        Map.of("KIE", null, "DEN", null, "SWE", null, "BER", null, "PRU", null)),
                new Province("BER", ProvinceType.COASTAL, new Nation("GERMANY"), true, null,
                        Map.of("MUN", null, "KIE", null, "BAL", null, "PRU", null, "SIL", null)),
                new Province("SIL", ProvinceType.INLAND, null, false, null,
                        Map.of("BOH", null, "GAL", null, "WAR", null, "PRU", null, "BER", null, "MUN", null)),
                new Province("PRU", ProvinceType.COASTAL, null, false, null,
                        Map.of("SIL", null, "BER", null, "BAL", null, "LVN", null, "WAR", null)),
                new Province("WAR", ProvinceType.INLAND, new Nation("RUSSIA"), true, null,
                        Map.of("GAL", null, "SIL", null, "PRU", null, "LVN", null, "MOS", null, "UKR", null)),
                new Province("LVN", ProvinceType.COASTAL, null, false, null,
                        Map.of("PRU", null, "WAR", null, "MOS", null, "STP", null, "BOT", null)),
                new Province("MOS", ProvinceType.INLAND, new Nation("RUSSIA"), true, null,
                        Map.of("WAR", null, "LVN", null, "STP", null, "FIN", null, "UKR", null, "SEV", null)),
                new Province("STP", ProvinceType.COASTAL, new Nation("RUSSIA"), true,
                        List.of(new Coast("north"), new Coast("south")),
                        Map.of("LVN", null, "MOS", null, "FIN", null, "NOR", null, "BOT", null, "BAR", null)),
                new Province("FIN", ProvinceType.COASTAL, null, false, null,
                        Map.of("MOS", null, "STP", null, "NOR", null, "SWE", null, "BOT", null)),
                new Province("NOR", ProvinceType.COASTAL, null, false, null,
                        Map.of("NWG", null, "STP", null, "FIN", null, "SWE", null, "SKA", null, "BAR", null)),
                new Province("SWE", ProvinceType.COASTAL, null, false, null,
                        Map.of("DEN", null, "SKA", null, "NOR", null, "FIN", null, "BOT", null, "BAL", null)),
                new Province("SKA", ProvinceType.SEA, null, false, null,
                        Map.of("NTH", null, "NWG", null, "NOR", null, "SWE", null, "DEN", null)),
                new Province("BAR", ProvinceType.SEA, null, false, null,
                        Map.of("NWG", null, "NOR", null, "STP", null, "FIN", null)),
                new Province("BOT", ProvinceType.SEA, null, false, null,
                        Map.of("LVN", null, "STP", null, "FIN", null, "SWE", null, "BAL", null)),
                new Province("UKR", ProvinceType.INLAND, null, false, null,
                        Map.of("WAR", null, "MOS", null, "SEV", null, "RUM", null, "BUD", null, "GAL", null)),
                new Province("SEV", ProvinceType.COASTAL, new Nation("RUSSIA"), true, null,
                        Map.of("MOS", null, "UKR", null, "RUM", null, "BLA", null, "ARM", null)),
                new Province("BLA", ProvinceType.SEA, null, false, null,
                        Map.of("RUM", null, "BUL", null, "CON", null, "SEV", null, "ARM", null)),
                new Province("CON", ProvinceType.COASTAL, new Nation("TURKEY"), true, null,
                        Map.of("BUL", null, "BLA", null, "SMY", null, "ANK", null, "AEG", null)),
                new Province("ANK", ProvinceType.COASTAL, new Nation("TURKEY"), true, null,
                        Map.of("CON", null, "SMY", null, "ARM", null, "BLA", null)),
                new Province("SMY", ProvinceType.COASTAL, new Nation("TURKEY"), true, null,
                        Map.of("CON", null, "ANK", null, "ARM", null, "SYR", null, "EAS", null, "AEG", null)),
                new Province("ARM", ProvinceType.COASTAL, null, false, null,
                        Map.of("SEV", null, "BLA", null, "ANK", null, "SMY", null, "SYR", null)),
                new Province("SYR", ProvinceType.COASTAL, null, false, null,
                        Map.of("SMY", null, "ARM", null, "EAS", null)),
                new Province("AEG", ProvinceType.SEA, null, false, null,
                        Map.of("GRE", null, "BUL", null, "CON", null, "SMY", null, "EAS", null, "ION", null)),
                new Province("EAS", ProvinceType.SEA, null, false, null,
                        Map.of("SMY", null, "SYR", null, "AEG", null, "ION", null)),
                new Province("TUN", ProvinceType.COASTAL, null, true, null,
                        Map.of("WES", null, "TYS", null, "ION", null))
        ));
    }
}
